### ISSUE TITLE
Not honoring GPLv3.0

### ISSUE THREAD

**Issue by dnorhoj** [Ner0ox/DaBabyAntiRickroll#1]
First of all, I'm glad that you forked my repository. And I think your extension is funny as heck, but as stated in the [original repository](https://github.com/dnorhoj/AntiRickRoll), my project uses the License GPLv3.0

GPLv3.0 specifies that modifications must be released under the same license.

I, therefore, ask you to change this repository's license to GPLv3.0

You can contact me via mail, daniel.norhoj@gmail.com if you have further questions.

**Comment by Ner0ox** [comment]
I'm very sorry, on firefox addons it was using apache or something like that. But I will change it asap.

**Comment by Ner0ox** [comment]
Changed it to GPLv3.0

**Comment by Ner0ox** [comment]
also I will change it on firefox once I get on my pc.
